export * from './anagrama'
export * from './contador_palabras'
export * from './dulceTruco'
export * from './header'
export * from './juegoEspacio'
export * from './numerosPerdidos'
export * from './palindromo'
export * from './piedra_papel_tijera'
